### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by WoutDeRijck** [kaistAI/prometheus#4]
Hello,

I've read your research paper with great interest and found your work quite remarkable. You've done a commendable job on your project. However, I had a query regarding the dataset you've used in your work.

In your study, I noticed you employed a dataset comprising 100k rows. I found this to be impressive. However, I wondered if this large dataset size is necessary for similar research? 

Currently, I am working in the educational field, where data gathering, especially data that's verified pedagogically, is indeed a costly and time-consuming process. Therefore, it'd be really helpful if you could provide some insights into:

1) The ideal size of the dataset that is needed to have results similar to yours?
2) Any pointers or suggestions on techniques that might be helpful to collect more cost and time-effective pedagogically sound data?
3) Any possible ways to replicate your research with a smaller dataset without compromising the reliability of the results?

**Comment by SeungoneKim** [comment]
@WoutDeRijck Hello Wout, thank you for your interest in our work!

Applying fine-grained evaluation in educational fields sounds very interesting!

I haven't ablated training with less data, but I guess including lots of score rubrics (we used 1K) during training would be important to not make the model get overfitted to one category.

I would suggest instead of training with Llama, you could try training based on Prometheus for your application. Of course, it would be important to first investigate whether Prometheus fails on what you would want it to do.

I'd love to hear more on this, please let me know!
