### ISSUE TITLE
Evaluation Code for AlpacaFarm, FLASK, MT-Bench

### ISSUE THREAD

**Issue by Haoxiang-Wang** [kaistAI/prometheus#8]
I am impressed by this work, and I want to use Prometheus to replace GPT-4 evaluator locally. 

Your paper mentioned experiments conducted on AlpacaFarm, FLASK, MT-Bench and Vicuna-Bench. Could you release your code for evaluating with Prometheus on these benchmarks?

**Comment by SeungoneKim** [comment]
@Haoxiang-Wang Hello Haoxiang, thank you for your interest, and sorry for the late response (I was busy due to PhD application and going to conferences😅)

Please refer to the code in evaluation/benchmark/run_absolute_scoring.py!
You could change the input_file_name argument into the JSON files included in evaluation/benchmark/data.
